version: '3.1'
services:
  db:
    image: postgres:14.9
    restart: always
    ports:
      -"5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER: "${DATABASE_USER}"
      - POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      - POSTGRES_DB: "${analytics}"
      - TZ: "America/Sao_Paulo"